### PR TITLE
adding dscout

### PR DESCRIPTION
**Pull request by JackKora**
# dscout

## PR Checklist
- [X] Added/updated company information to the ./companies.json file
- [X] `cd` into the `readme_generator` folder and ran `mix generate_readme`
- [X] Committed companies.json and the newly generated README.md

### CODE REVIEW

**Review by dkarter — APPROVED** [review]
Great! Thank you @ykorabelnikov !!!

**Comment by JackKora** [comment]
@dkarter, not a big deal but I noticed that dscout was added at the bottom even though I added it in alphabetical order in the JSON file (because they all seem to be in alphabetical order). Is that by design?

**Comment by dkarter** [comment]
@ykorabelnikov fixed!

**Comment by JackKora** [comment]
@dkarter thanks!

**Pull request merged**
